name: PR Check CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Clone nuttx repo
      run: |
        echo "Clone nuttx repo"
        git clone https://github.com/apache/incubator-nuttx.git
    - name: Check patch
      run: |
        echo "Check patch"
        git log --oneline -10
        prcommit=`git log --no-merges --format=format:%H | head -1`
        ../incubator-nuttx/tools/checkpatch.sh -c $prcommit
    - name: Install tools
      run: |
        echo "Install tools"
    - name: Run builds
      run: |
        echo "Run PR check build"

